#!/bin/bash
#Colours
greenColour="\e[0;32m\033[1m"
endColour="\033[0m\e[0m"
redColour="\e[0;31m\033[1m"
blueColour="\e[0;34m\033[1m"
yellowColour="\e[0;33m\033[1m"
purpleColour="\e[0;35m\033[1m"
turquoiseColour="\e[0;36m\033[1m"
grayColour="\e[0;37m\033[1m"

echo -e "${yellowColour}[*] Interfaces Red [*]${endColour}\n"
touch direcciones
touch interfaces
touch ips
ifconfig | grep "inet " | awk '{print $2}' > direcciones
ifconfig -s | awk  'NR>1{print $1}' > interfaces
paste interfaces direcciones > ips
echo -e " ${yellowColour}\tInterfaz   Direccion IP${endColour}"
awk '{print "\t ""\033[33m" $1 "\t  "$2}' ips
x=0
while [ $x -eq 0 ]
do
printf "\n${turquoiseColour}[*] Introduzca interfaz a examinar: ${endColour}"
read variable
var=$(cat interfaces | grep "$variable")
if [ "$variable" = "$var" ]; then
	echo "hoa"
	x=1
else
	echo -e "${redColour}Interfaz erronea${endColour}"
fi
done
rm {direcciones,interfaces,ips}
