#!/bin/bash
# Reset
Color_Off="\[\033[0m\]"       # Text Reset

# Regular Colors
Black="\[\033[0;30m\]"        # Black
Red="\[\033[0;31m\]"          # Red
Green="\[\033[0;32m\]"        # Green
Yellow="\[\033[0;33m\]"       # Yellow
Blue="\[\033[0;34m\]"         # Blue
Purple="\[\033[0;35m\]"       # Purple
Cyan="\[\033[0;36m\]"         # Cyan
White="\[\033[0;37m\]"        # White

echo -e "REGULAR COLORS"
echo -e "${Black}hola${Color_Off}"
echo -e "${Red}hola${Color_Off}"
echo -e "${Green}hola${Color_Off}"
echo -e "${Yellow}hola${Color_Off}"
echo -e "${Blue}hola${Color_Off}"
echo -e "${Purple}hola${Color_Off}"
echo -e "${Cyan}hola${Color_Off}"
echo -e "${White}hola${Color_Off}"

# Bold
BBlack="\[\033[1;30m\]"       # Black
BRed="\[\033[1;31m\]"         # Red
BGreen="\[\033[1;32m\]"       # Green
BYellow="\[\033[1;33m\]"      # Yellow
BBlue="\[\033[1;34m\]"        # Blue
BPurple="\[\033[1;35m\]"      # Purple
BCyan="\[\033[1;36m\]"        # Cyan
BWhite="\[\033[1;37m\]"       # White


echo -e "BOLDS COLORS"
echo -e "${BBlack}hola${Color_Off}"
echo -e "${BRed}hola${Color_Off}"
echo -e "${BGreen}hola${Color_Off}"
echo -e "${BYellow}hola${Color_Off}"
echo -e "${BBlue}hola${Color_Off}"
echo -e "${BPurple}hola${Color_Off}"
echo -e "${BCyan}hola${Color_Off}"
echo -e "${BWhite}hola${Color_Off}"

# Underline
UBlack="\[\033[4;30m\]"       # Black
URed="\[\033[4;31m\]"         # Red
UGreen="\[\033[4;32m\]"       # Green
UYellow="\[\033[4;33m\]"      # Yellow
UBlue="\[\033[4;34m\]"        # Blue
UPurple="\[\033[4;35m\]"      # Purple
UCyan="\[\033[4;36m\]"        # Cyan
UWhite="\[\033[4;37m\]"       # White


echo -e "UNDERLINERS COLORS"
echo -e "${UBlack}hola${Color_Off}"
echo -e "${URed}hola${Color_Off}"
echo -e "${UGreen}hola${Color_Off}"
echo -e "${UYellow}hola${Color_Off}"
echo -e "${UBlue}hola${Color_Off}"
echo -e "${UPurple}hola${Color_Off}"
echo -e "${UCyan}hola${Color_Off}"
echo -e "${UWhite}hola${Color_Off}"

# Background
On_Black="\[\033[40m\]"       # Black
On_Red="\[\033[41m\]"         # Red
On_Green="\[\033[42m\]"       # Green
On_Yellow="\[\033[43m\]"      # Yellow
On_Blue="\[\033[44m\]"        # Blue
On_Purple="\[\033[45m\]"      # Purple
On_Cyan="\[\033[46m\]"        # Cyan
On_White="\[\033[47m\]"       # White

echo -e "BACKGROUNDS COLORS"
echo -e "${On_Black}hola${Color_Off}"
echo -e "${On_Red}hola${Color_Off}"
echo -e "${On_Green}hola${Color_Off}"
echo -e "${On_Yellow}hola${Color_Off}"
echo -e "${On_Blue}hola${Color_Off}"
echo -e "${On_Purple}hola${Color_Off}"
echo -e "${On_Cyan}hola${Color_Off}"
echo -e "${On_White}hola${Color_Off}"

# High Intensty
IBlack="\[\033[0;90m\]"       # Black
IRed="\[\033[0;91m\]"         # Red
IGreen="\[\033[0;92m\]"       # Green
IYellow="\[\033[0;93m\]"      # Yellow
IBlue="\[\033[0;94m\]"        # Blue
IPurple="\[\033[0;95m\]"      # Purple
ICyan="\[\033[0;96m\]"        # Cyan
IWhite="\[\033[0;97m\]"       # White

echo -e "HIGH INTENSITY COLORS"
echo -e "${IBlack}hola${Color_Off}"
echo -e "${IRed}hola${Color_Off}"
echo -e "${IGreen}hola${Color_Off}"
echo -e "${IYellow}hola${Color_Off}"
echo -e "${IBlue}hola${Color_Off}"
echo -e "${IPurple}hola${Color_Off}"
echo -e "${ICyan}hola${Color_Off}"
echo -e "${IWhite}hola${Color_Off}"


# Bold High Intensty
BIBlack="\[\033[1;90m\]"      # Black
BIRed="\[\033[1;91m\]"        # Red
BIGreen="\[\033[1;92m\]"      # Green
BIYellow="\[\033[1;93m\]"     # Yellow
BIBlue="\[\033[1;94m\]"       # Blue
BIPurple="\[\033[1;95m\]"     # Purple
BICyan="\[\033[1;96m\]"       # Cyan
BIWhite="\[\033[1;97m\]"      # White

echo -e "BLOD HIGH INTENSITY COLORS"
echo -e "${BIBlack}hola${Color_Off}"
echo -e "${BIRed}hola${Color_Off}"
echo -e "${BIGreen}hola${Color_Off}"
echo -e "${BIYellow}hola${Color_Off}"
echo -e "${BIBlue}hola${Color_Off}"
echo -e "${BIPurple}hola${Color_Off}"
echo -e "${BICyan}hola${Color_Off}"
echo -e "${BIWhite}hola${Color_Off}"

# High Intensty backgrounds
On_IBlack="\[\033[0;100m\]"   # Black
On_IRed="\[\033[0;101m\]"     # Red
On_IGreen="\[\033[0;102m\]"   # Green
On_IYellow="\[\033[0;103m\]"  # Yellow
On_IBlue="\[\033[0;104m\]"    # Blue
On_IPurple="\[\033[10;95m\]"  # Purple
On_ICyan="\[\033[0;106m\]"    # Cyan
On_IWhite="\[\033[0;107m\]"   # White


echo -e "High Intensty backgrounds COLORS"
echo -e "${On_IBlack}hola${Color_Off}"
echo -e "${On_IRed}hola${Color_Off}"
echo -e "${On_IGreen}hola${Color_Off}"
echo -e "${On_IYellow}hola${Color_Off}"
echo -e "${On_IBlue}hola${Color_Off}"
echo -e "${On_IPurple}hola${Color_Off}"
echo -e "${On_ICyan}hola${Color_Off}"
echo -e "${On_IWhite}hola${Color_Off}"



